name: cdk-express-pipeline-github-diff
description: Outputs the CDK Express Pipeline diff on a GitHub PR
author: rehanvdm

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: heart
  color: red

# Define your inputs here.
inputs:
  cloud-assembly-directory:
    description: The directory containing the CDK Cloud Assembly, defaults to 'cdk.out'
    default: 'cdk.out'

runs:
  using: node20
  main: dist/index.js
