name: cdk-express-pipeline-github-diff
description: Outputs the CDK Express Pipeline diff on a GitHub PR
author: rehanvdm

inputs:
  mode:
    description: |
      The mode to run the action in. Options are:
        - `generate`: Generates, saves the diff of the CDK Express Pipeline to file and caches it.
        - `print`: Reads all the generated diffs from cache and updates the PR description with the diff.
    required: true
  cloud-assembly-directory:
    description: |
      The directory containing the CDK Cloud Assembly.
      Required for `mode: generate`
      Defaults to 'cdk.out'
    required: false
  stack-selectors:
    description: |
      The stack selectors to use for the diff. Multiple selectors can be provided as a comma-separated list.
      Required for `mode: generate`
      Defaults to '**' (all stacks).
    required: false
  github-token:
    description: |
      GitHub token for API access to read PR action/job info, update the PR description and read & write to the cache
    required: true
  job-name:
    description: |
      The name of the job, to correctly link to the action logs when using a Matrix.
    required: false

runs:
  using: node20
  main: FORCE_COLOR=1 dist/index.cjs
